const playerRating = document.querySelector('[data-rating]')
const playerName = document.querySelector('[data-name]')
const playerPosition = document.querySelector('[data-position]')
const playerNation = document.querySelector('[data-nation]')
const playerClub = document.querySelector('[data-club]')
const playerPlayer = document.querySelector('[data-player]')
const form = document.querySelector('[data-form]')
const button = document.querySelector('[data-button]')
form.addEventListener('submit', function(e) { 
  e.preventDefault()
  fetch(`https://www.futbin.com/search?year=20&extra=1&term=${form.value}`)
  .then(api => api.json())
  .then(json => json[0].name)
  console.log(json)
  })