const playerRating = document.querySelector('[data-rating]')
const playerName = document.querySelector('[data-name]')
const playerPosition = document.querySelector('[data-position]')
const playerNation = document.querySelector('[data-nation]')
const playerClub = document.querySelector('[data-club]')
const playerPlayer = document.querySelector('[data-player]')
const form = document.querySelector('[data-form]')
const button = document.querySelector('[data-button]')
const input = document.querySelector('[data-input]')
form.addEventListener('submit', function(e) { 
  e.preventDefault()
  fetch(`https://www.futbin.com/search?year=20&extra=1&term=${input.value}`)
  .then(api => api.json())
  .then(json => {
    const n = document.createTextNode(json[0].name)
    playerName.append(n)
    const r = document.createTextNode(json[0].rating)
    playerRating.append(r)
    const p = document.createTextNode(json[0].position)
    playerPosition.append(p)
    const na = playerNation.setAttribute('src', json[0].nation_image.replace('cdn.', ''))
    const pl = playerPlayer.setAttribute('src', json[0].image.replace('cdn.', ''))
    const c = playerClub.setAttribute('src', json[0].club_image.replace('cdn.', ''))    
  })  
  })